### ISSUE TITLE
Warning on rake 0.9.4

### ISSUE THREAD

**Issue by yuanying** [TwP/webby#7]
I had a warning on rake 0.9.4.

```
$ webby -T                               
WARNING: Global access to Rake DSL methods is deprecated.  Please include
    ...  Rake::DSL into classes and modules which use the Rake DSL methods.
WARNING: DSL method Webby::Apps::Main#import called at /Users/hoge/.rvm/gems/ruby-1.8.7-p352@webby/gems/webby-0.9.4/lib/webby/apps/main.rb:177:in `import_default_tasks'
WARNING: DSL method Webby::Apps::Main#import called at /Users/hoge/.rvm/gems/ruby-1.8.7-p352@webby/gems/webby-0.9.4/lib/webby/apps/main.rb:181:in `import_website_tasks'
```

**Comment by TwP** [comment]
On Aug 8, 2011, at 7:35 PM, yuanying wrote:

> I had a warning on rake 0.9.4.
> 
>    $ webby -T  
>    WARNING: Global access to Rake DSL methods is deprecated.  Please include
>        ...  Rake::DSL into classes and modules which use the Rake DSL methods.
>    WARNING: DSL method Webby::Apps::Main#import called at /Users/hoge/.rvm/gems/ruby-1.8.7-p352@webby/gems/webby-0.9.4/lib/webby/apps/main.rb:177:in `import_default_tasks'
>    WARNING: DSL method Webby::Apps::Main#import called at /Users/hoge/.rvm/gems/ruby-1.8.7-p352@webby/gems/webby-0.9.4/lib/webby/apps/main.rb:181:in`import_website_tasks'

Webby is no longer under active development. I'm sorry to disappoint you, but I do not have the extra time to devote to the project.

Please look into nanoc http://nanoc.stoneship.org/ - it is actively maintained and offers a very similar feature set to Webby.

Blessings,
TwP

**Comment by billspat** [comment]
Webby is (was) awesome.  Used it very successfully in the past. 

But if webby is no longer developed, could you please also indicate so on the RubyForge home page as well as GitHub?  That is the page that Google finds. 

http://webby.rubyforge.org/

I'm not asking for a free fix, just a way to let unsuspecting RubyForge users like me know it's not going to work on an updated machine before we waste time getting started.
